version: '3.1'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./project:/var/www/
    depends_on:
      - php

  php:
    build: ./php
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db_name
    volumes:
      - ./project:/var/www/
      - ./php.ini-production:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - 8888:80
    depends_on:
      - db